- name: Check if MicroK8s is running
  shell: microk8s status --wait-ready >/dev/null 2>&1
  register: microk8s_check
  ignore_errors: true
  changed_when: false

- name: Print warning if MicroK8s is not installed
  debug:
    msg: "MicroK8s is NOT installed yet. Proceeding to install.."
  when: microk8s_check.rc != 0

- name: Set fact if MicroK8s is running
  set_fact:
    microk8s_running: "{{ microk8s_check.rc == 0 }}"

- block:
    - name: Install MicroK8s
      command: snap install microk8s --classic --channel={{ microk8s_version }}
      environment:
        PATH: "/snap/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    - name: Add 'ubuntu' user to microk8s group
      user:
        name: ubuntu
        groups: microk8s
        append: yes

    - name: Disable Snap Auto Updates (optional)
      command: snap set system refresh.retain=2
      when: not microk8s_disable_snap_autoupdate
      environment:
        PATH: "/snap/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    - name: Enable MicroK8s plugins
      become: true
      shell: >
        microk8s enable {{ item.key }} {{ item.value if item.value is string else '' }}
      args:
        executable: /bin/bash
      environment:
        PATH: "/snap/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      loop: "{{ microk8s_plugins | dict2items }}"
      when: item.value != false

    - name: Ensure ~/.kube directory exists for ubuntu
      become: true
      file:
        path: /home/ubuntu/.kube
        state: directory
        mode: '0700'
        owner: ubuntu
        group: ubuntu

    - name: Export MicroK8s config to ~/.kube/config for ubuntu
      become: true
      shell: microk8s config > /home/ubuntu/.kube/config
      args:
        executable: /bin/bash
      environment:
        PATH: "/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    - name: Fix permissions for kubeconfig
      become: true
      file:
        path: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: '0600'

  when: not microk8s_running
