- name: Enable Helm3 in MicroK8s
  command: microk8s enable helm3
  become: true
  environment:
    PATH: "/snap/bin:/usr/sbin:/usr/bin:/sbin:/bin"

- name: Add NGINX ingress Helm repo
  command: microk8s helm3 repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  become: true

- name: Update Helm repos
  command: microk8s helm3 repo update
  become: true

- name: Install ingress-nginx via Helm
  command: microk8s helm3 install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace
  become: true

- name: Wait for ingress controller to be ready
  shell: |
    microk8s kubectl -n ingress-nginx rollout status deployment ingress-nginx-controller --timeout=180s
  become: true

