- name: Install MicroK8s on EC2
  hosts: microk8s
  become: true
  tasks:
    - name: Install snapd and dependencies
      yum:
        name:
          - snapd
          - curl
        state: present
        update_cache: yes

    - name: Enable and start snapd.socket
      systemd:
        name: snapd.socket
        enabled: yes
        state: started

    - name: Wait for snap to be ready
      shell: "sleep 10"

    - name: Create /snap symlink
      file:
        src: /var/lib/snapd/snap
        dest: /snap
        state: link
        force: yes

    - name: Install MicroK8s
      command: snap install microk8s --classic
      environment:
        PATH: "/snap/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    - name: Add ec2-user to microk8s group
      user:
        name: ec2-user
        groups: microk8s
        append: yes

    - name: Enable MicroK8s DNS
      command: microk8s enable dns
      environment:
        PATH: "/snap/bin:/usr/sbin:/usr/bin:/sbin:/bin"

